repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Update this line with the latest revision
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
# -   repo: https://gitlab.com/PyCQA/flake8
-   repo: https://github.com/pycqa/flake8.git  # Update this line with the correct repository URL
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
        #files: ^my_appname/|^test_suite_name/
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
